# fly.toml file generated for nodemcu-server on 2022-09-26T21:11:33+03:00

app = "nodemcu-server"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[build.args]
  MODE="production"
  NODE_ENV="production"
  # NPM_CONFIG_PRODUCTION=true
  # USE_NPM_INSTALL=true

[env]
  MQTT_PORT = "1883"
  MQTT_WS_PORT = "8888"

[[services]]
  internal_port = 1883
  processes = ["app"]
  protocol = "tcp"
  
  [[services.ports]]
    port = 1883

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"

[[services]]
  internal_port = 8888
  processes = ["app"]
  protocol = "tcp"
  
  [[services.ports]]
    port = 8888

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"
